name: Azure Test Connect

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  login-test:
    runs-on: ubuntu-latest
    steps:
      - name: Azure Login
        uses: azure/login@f6f2c6c6a6c8c3b6f3e3a1e3e3c3a3f3c3a3f3e3
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          auth-type: federated

      - name: Show Azure Account
        run: az account show
