# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Continuous Integration Build

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - '.github/workflows/**'
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.3.1
    - name: Restore dependencies
      run: dotnet restore
    - name: Build all .csproj files
      run: |
        for file in $(find . -name '*.csproj'); do
          dotnet build $file --no-restore
        done

    - name: Build all .sqlproj files
      run: |
        for file in $(find . -name '*.sqlproj'); do
          msbuild $file /p:Configuration=Release
        done
#    - name: Test
#     run: dotnet test --no-build --verbosity normal
