name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    env:
      BLAZOR_SOLUTION: 'Holonet.Databank.App.sln'
      SQL_SOLUTION: 'Holonet.Databank.DB.sln'

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Install Visual Studio Build Tools
        run: choco install visualstudio2019buildtools --package-parameters "--add Microsoft.VisualStudio.Workload.MSBuildTools"
      
      - name: Setup .NET 8 SDK
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 8.0.x

      - name: Restore dependencies for Blazor Web App
        run: dotnet restore ${{ env.BLAZOR_SOLUTION }}

      - name: Restore dependencies for SQL Project
        run: msbuild /restore ${{ env.SQL_SOLUTION }}

      - name: Build Blazor Web App
        run: dotnet build ${{ env.BLAZOR_SOLUTION }} --configuration Release --no-restore

      - name: Build SQL Project
        run: msbuild ${{ env.SQL_SOLUTION }} /p:Configuration=Release

      - name: Test Blazor Web App
        run: dotnet test ${{ env.BLAZOR_SOLUTION }} --no-restore --verbosity normal

      - name: Test SQL Project
        run: dotnet test ${{ env.SQL_SOLUTION }} --no-restore --verbosity normal
