name: CI Pipeline

on:
  push:
    branches:
      - main
    paths-ignore:
      - '.github/workflows/**'
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    env:
      APP_SOLUTION: 'Holonet.Databank.App.sln'
      SQL_SOLUTION: 'Holonet.Databank.DB.sln'

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Visual Studio Build Tools
        run: choco install visualstudio2019buildtools --package-parameters "--add Microsoft.VisualStudio.Workload.MSBuildTools --add Microsoft.Component.MsBuild" 
        
      - name: Setup .NET 8 SDK
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 8.0.x

      - name: Restore dependencies for Blazor Web App
        run: dotnet restore ${{ env.APP_SOLUTION }}
        
      - name: Restore dependencies
        run: msbuild /restore ${{ env.SQL_PROJECT }}

      - name: Build Blazor Web App
        run: dotnet build ${{ env.APP_SOLUTION }} --configuration Release --no-restore
      
      - name: Build SQL Project
        run: msbuild ${{ env.SQL_PROJECT }} /p:Configuration=Release

      #- name: Deploy SQL Changes
      #  uses: Azure/sql-action@v2.3
      #  with:
      #    connection-string: 'your-connection-string'
      #    action: 'Publish'
      #    dacpac-file: 'path/to/your/output.dacpac'
