name: CI Pipeline

on:
  push:
    branches:
      - main
    paths-ignore:
      - '*.yml'
  pull_request:
    branches:
      - main
    paths-ignore:
      - '*.yml'

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      APP_SOLUTION: 'Holonet.Databank.App.sln'

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Setup .NET 8 SDK
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 8.0.x

      - name: Restore dependencies for Blazor Web App
        run: dotnet restore ${{ env.APP_SOLUTION }}

      - name: Build Blazor Web App
        run: dotnet build ${{ env.APP_SOLUTION }} --configuration Release --no-restore
        
#      - name: Test Blazor Web App
#       run: dotnet test ${{ env.APP_SOLUTION }} --no-restore --verbosity normal
