name: Function App CI/CD
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths-ignore:
      - '.github/workflows/**'
  pull_request:
    branches:
      - main
env:
  DOTNET_VERSION: '9.0.x'
  CONFIGURATION: 'Release'  
  FUNCAPP_NAME: 'Holonet-Func-Databank-8108'
  RESOURCE_GROUP: 'Holonet'
  # Add additional global environment variables here

jobs:
  build-project:
    name: Build Function Project
    runs-on: ubuntu-latest
    env:
      APP_SOLUTION: 'Holonet.Databank.App-deploy.sln'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Restore dependencies
        run: dotnet restore ${{ env.APP_SOLUTION }}

      - name: Build Solution
        run: dotnet build --configuration ${{ env.CONFIGURATION }} ${{ env.APP_SOLUTION }}
  
  publish-appfunctions:
    name: Publish Function App
    needs: build-project
    runs-on: ubuntu-latest
    env:
      PUBLISH_DIR: ./publish
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Publish
        run: dotnet publish ./src/Holonet.Databank.AppFunctions/Holonet.Databank.AppFunctions.csproj --configuration ${{ env.CONFIGURATION }} --output ${{ env.PUBLISH_DIR }}
        
      - name: Login to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy with Azure Functions Core Tools
        run: |
          npm install -g azure-functions-core-tools@4 --unsafe-perm true
          cd publish
          func azure functionapp publish ${{ env.FUNCAPP_NAME }} \
            --dotnet-isolated \
            --no-build \
            --no-bundle 
