name: App CI/CD

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths-ignore:
      - '.github/workflows/**'
  pull_request:
    branches:
      - main

env:
  DOTNET_VERSION: '9.0.x'
  CONFIGURATION: 'Release'
  WEBAPP_NAME: 'Holonet-App-Databank-8108'
  WEBAPI_NAME: 'Holonet-Api-Databank-8108'
  FUNCAPP_NAME: 'Holonet-Func-Databank-8108'
  # Add additional global environment variables here

jobs:
  build-solution:
    name: Build Solution
    runs-on: ubuntu-latest
    env:
      APP_SOLUTION: 'Holonet.Databank.App-deploy.sln'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Restore dependencies
        run: dotnet restore ${{ env.APP_SOLUTION }}

      - name: Build Solution
        run: dotnet build --configuration ${{ env.CONFIGURATION }} ${{ env.APP_SOLUTION }}

  publish-api:
    name: Publish API
    needs: build-solution
    runs-on: ubuntu-latest
    env:
      PUBLISH_DIR: ./publish/api
      # Add secrets or deployment environment variables here (e.g., API_KEY: ${{ secrets.API_KEY }})
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Publish
        run: dotnet publish --configuration ${{ env.CONFIGURATION }} --output ${{ env.PUBLISH_DIR }} src/Holonet.Databank.API/Holonet.Databank.API.csproj

      - name: Login to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure Web App
        id: deploy-to-api
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.WEBAPI_NAME }}
          slot-name: 'Production'
          package: ${{ env.PUBLISH_DIR }}

  publish-web:
    name: Publish Web
    needs: build-solution
    runs-on: ubuntu-latest
    env:
      PUBLISH_DIR: ./publish/web
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Publish
        run: dotnet publish --configuration ${{ env.CONFIGURATION }} --output ${{ env.PUBLISH_DIR }} src/Holonet.Databank.Web/Holonet.Databank.Web.csproj

      - name: Login to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.WEBAPP_NAME }}
          slot-name: 'Production'
          package: ${{ env.PUBLISH_DIR }}

  publish-appfunctions:
    name: Publish Function App
    needs: build-solution
    runs-on: ubuntu-latest
    env:
      PUBLISH_DIR: ${{runner.temp}}/publish/appfunctions
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Publish
        run: dotnet publish src/Holonet.Databank.AppFunctions/Holonet.Databank.AppFunctions.csproj --configuration ${{ env.CONFIGURATION }} --output ${{ env.PUBLISH_DIR }}

      - name: Login to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}      

      - name: Deploy to Azure Function App
        id: deploy-to-function
        uses: azure/functions-action@v1
        with:
          app-name: ${{ env.FUNCAPP_NAME }}
          package: ${{ env.PUBLISH_DIR }}
