name: Web and API CI/CD

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths-ignore:
      - '.github/workflows/**'
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      APP_SOLUTION: 'Holonet.Databank.App-deploy.sln'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Restore dependencies
        run: dotnet restore ${{ env.APP_SOLUTION }}

      - name: Build solution
        run: dotnet build ${{ env.APP_SOLUTION }} --configuration Release --no-restore

      - name: Publish Blazor app
        run: dotnet publish ./Holonet.Databank.Web/Holonet.Databank.Web.csproj --configuration Release --output ./publish_blazor

      - name: Publish API
        run: dotnet publish ./Holonet.Databank.API/Holonet.Databank.API.csproj --configuration Release --output ./publish_api

      - name: Publish Function App
        run: dotnet publish ./Holonet.Databank.AppFunctions/Holonet.Databank.AppFunctions.csproj --configuration Release --framework net8.0 --output ./publish_function

      - name: Upload Blazor artifact
        uses: actions/upload-artifact@v4
        with:
          name: blazor_app
          path: ./publish_blazor

      - name: Upload API artifact
        uses: actions/upload-artifact@v4
        with:
          name: api_app
          path: ./publish_api

      - name: Upload Function App artifact
        uses: actions/upload-artifact@v4
        with:
          name: function_app
          path: ./publish_function

  deploy_blazor:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download Blazor artifact
        uses: actions/download-artifact@v4
        with:
          name: blazor_app
          path: ./publish

      - name: Login to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'Holonet-App-Databank-8108'
          slot-name: 'Production'
          package: ./publish

  deploy_api:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download API artifact
        uses: actions/download-artifact@v4
        with:
          name: api_app
          path: ./publish

      - name: Login to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure Web App
        id: deploy-to-api
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'Holonet-Api-Databank-8108'
          slot-name: 'Production'
          package: ./publish
  
  deploy_function:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download Function artifact
        uses: actions/download-artifact@v4
        with:
          name: function_app
          path: ./publish

      - name: Login to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure Function App
        id: deploy-to-function
        uses: azure/functions-action@v1
        with:
          app-name: 'Holonet-Func-Databank-8108'
          package: ./publish
