name: SQL Project CI/CD

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths-ignore:
      - '.github/workflows/**'
  pull_request:
    branches:
      - main
jobs:
  Build:
    runs-on: windows-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2
        
      - name: Build SQL Project
        run: msbuild.exe ./src/Holonet.Databank.DB/Holonet.Databank.DB.sqlproj /p:Configuration=Release

      - name: Publish SQL Artifact
        uses: actions/upload-artifact@v4
        with:
          name: SQLDB
          path: ${{ github.workspace }}\src\Holonet.Databank.DB\bin\release\

  DeploySQLDB:
    needs: Build
    runs-on: ubuntu-22.04
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      
      - name: Download Artifact Containing DACPAC
        uses: actions/download-artifact@v4
        with:
          name: SQLDB
          path: ./dacpac

      - name: Install sqlpackage
        run: |
          sudo apt-get update
          sudo apt-get install -y curl apt-transport-https
          curl -sSL https://packages.microsoft.com/keys/microsoft.asc | sudo apt-key add -
          sudo add-apt-repository "$(curl -sSL https://packages.microsoft.com/config/ubuntu/22.04/prod.list | sudo tee /etc/apt/sources.list.d/mssql-release.list)"
          sudo apt-get update
          sudo apt-get install -y mssql-tools
          echo 'export PATH="$PATH:/opt/mssql-tools/bin"' >> ~/.bashrc
          source ~/.bashrc
          
      - name: Verify sqlpackage installation
        run: sqlpackage /?
          
      - name: Login to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      
      - name: Run pre-publish SQL script
        uses: azure/sql-action@v2.3
        with:
          connection-string: '${{ secrets.AZURE_SQL_CONNECTION }}'
          path: './infrastructure/db-scripts/disable-change-tracking.sql'
          action: 'publish'
      
      - name: Deploy DACPAC to Azure SQL
        uses: azure/sql-action@v2.3
        with:
          connection-string: '${{ secrets.AZURE_SQL_CONNECTION }}'
          path: 'dacpac/Holonet.Databank.DB.dacpac'
          action: 'publish'          
          arguments: >
            /p:BlockOnPossibleDataLoss=false
            /p:ExcludeObjectTypes=Users;Logins;RoleMembership;Permissions
            
      - name: Run pre-publish SQL script
        uses: azure/sql-action@v2.3
        with:
          connection-string: '${{ secrets.AZURE_SQL_CONNECTION }}'
          path: './infrastructure/db-scripts/enable-change-tracking.sql'
          action: 'publish'
